#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

source $OPENSHIFT_CARTRIDGE_SDK_BASH

pushd ${OPENSHIFT_REPO_DIR} > /dev/null
if [ "$(ls -A db/migrate)" ]; then
  PADRINO_ENV=production bundle exec rake sq:migrate
else
  echo "The migration folder is empty, skipping rake sq:migrate"
fi
popd > /dev/null
